name: resilience_muscle
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  slidy: ^4.0.3
  flutter_triple: ^2.0.1
  firebase_core: ^2.4.1
  firebase: ^9.0.3
  flutter_bloc: ^8.1.1
  asuka: ^2.1.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  google_sign_in: ^6.1.3
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  json_annotation: ^4.8.1
  step_progress_indicator: ^1.0.2
  google_fonts: ^4.0.4
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0
  smooth_page_indicator: ^1.0.0+2
  mask_text_input_formatter: ^2.4.0
  horizontal_picker: ^1.2.0
  logger: ^1.4.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  hive:
  hive_flutter:
  hive_generator:
  image_picker:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  modular_test: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/appIcons/

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/jura/JuraBook.ttf
        - asset: assets/fonts/jura/JuraLight.ttf

    - family: JuraDemiBold
      fonts:
        - asset: assets/fonts/jura/JuraDemiBold.ttf

    - family: JuraMedium
      fonts:
        - asset: assets/fonts/jura/JuraMedium.ttf
